[package]
name = "raisehell"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
num = "0.4.3"
poise = "0.6.1"
rand = "0.8.5"
tokio = { version = "1.43.0", features = ["full"] }

[lib]
name = "raisehell"
path = "src/lib.rs"
